# Generated by Django 4.0.5 on 2022-07-10 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_mvt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacion',
            name='cantidad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operacion',
            name='hora',
            field=models.DateTimeField(default="2022-06-30 15:22"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operacion',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
